Device: cuda:0
----------------------(train)----------------------
Epoch 0/15
---------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 65, in <module>
    no_wandb=args.no_wandb,
  File "/media/ssd4t/mana/GANomaly/model.py", line 50, in train
    print(dataloader.size())
AttributeError: 'DataLoader' object has no attribute 'size'
